### ISSUE TITLE
Figures are double

### ISSUE THREAD

**Issue by simonrb2000** [mvdklip/Domoticz-myenergi#2]
Home consumption and import from grid are twice what they should be. Car charging is correct. I do have two Zappi’s with one being a slave. Not sure if that causing the issue.

**Comment by mvdklip** [comment]
Thanks for sharing. I am currently adding up figures for multiple Zappi's. Apparantly in your case each Zappi is reporting totals for home consumption and grid but their own figure for car charging. Can you please confirm that car charging is correct? If one Zappi is charging you see only the consumption for that charger, if both are charging you see the total?

**Comment by mvdklip** [comment]
@simonrb2000 please confirm so I can make a fix. Current code is assuming that all Zappi's report their own data but according to your report this is not the case. I need to make new assumptions and need your help for this as I don't have two Zappi's myself. :-)
